### ISSUE TITLE
Hello is it a working launcher?

### ISSUE THREAD

**Issue by VinkyV** [TheDevelo/minelaunch#1]
!!!if its a working launcher can i see how its look? And i get this error (how can i fix this?):
*warning: unused variable: `minecraft_path`
   --> src\main.rs:456:29
    |
456 | fn launch_minecraft_version(minecraft_path: &str, version: &VersionSpec) {
    |                             ^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_minecraft_path`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `version`
   --> src\main.rs:456:51
    |
456 | fn launch_minecraft_version(minecraft_path: &str, version: &VersionSpec) {
    |                                                   ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_version`

warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target\debug\minelaunch.exe Cargo.toml`
Java installation not found
Downloading Java for windows-x64
Extracting Java
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: TarError { desc: "failed to iterate over archive", io: Custom { kind: InvalidInput, error: "invalid gzip header" } } }', src\main.rs:244:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\minelaunch.exe Cargo.toml` (exit code: 101)*

**Comment by TheDevelo** [comment]
This is not an active project, nor is it a finished one. If you want to have a crack at finishing it, be my guest, but there are almost definitely other projects that fill the same role and are fully featured.
As for the error, the Java downloader is broken, and probably has to be rewritten. Has something to do with a change they made to the URL or Headers, but that's all I remember.
Aside from that, the rest of what's implemented should work, but I also haven't implemented the part that launches the game, only the downloader.
